from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional, Sequence


@dataclass(frozen=True)
class HfUploadResult:
    repo_id: str
    repo_url: str
    path_in_repo: str
    commit_message: str
    created_repo: bool
    private: Optional[bool]
    upload_result: Any


_DEFAULT_IGNORE = ["**/__pycache__/**", "**/.DS_Store", "**/.pytest_cache/**"]


def ensure_dataset_card(export_root: Path, *, repo_id: str, stats: dict[str, Any]) -> Path:
    card_path = export_root / "README.md"
    if card_path.exists():
        return card_path
    total_rows = int(stats.get("sft_rows", 0)) + int(stats.get("grpo_rows", 0))
    if total_rows < 1000:
        size_category = "n<1K"
    elif total_rows < 10000:
        size_category = "1K<n<10K"
    elif total_rows < 100000:
        size_category = "10K<n<100K"
    else:
        size_category = "n>100K"
    content = """---
pretty_name: {pretty_name}
tags:
- multimodal
- scientific-papers
- scidatapipe
- top-papers-graph
size_categories:
- {size_category}
---

# {repo_id}

Export generated by `top-papers-graph export-scidatapipe`.

## Contents

- `sft.jsonl`: supervised fine-tuning samples
- `grpo.jsonl`: GRPO / preference-style samples
- `normalized_task1/`: normalized trajectory files
- `normalized_task2/`: normalized validation bundles
- `export_summary.json`: build summary and counts
- `assets/`: copied multimodal assets referenced by samples

## Summary

- SFT rows: {sft_rows}
- GRPO rows: {grpo_rows}
- Task1 inputs: {task1_inputs}
- Task2 inputs: {task2_inputs}
""".format(
        pretty_name=repo_id.split("/")[-1],
        size_category=size_category,
        repo_id=repo_id,
        sft_rows=stats.get("sft_rows", 0),
        grpo_rows=stats.get("grpo_rows", 0),
        task1_inputs=stats.get("discovered_task1_files", 0),
        task2_inputs=stats.get("discovered_task2_inputs", 0),
    )
    card_path.write_text(content, encoding="utf-8")
    return card_path


def upload_export_to_hf(
    export_root: Path,
    *,
    repo_id: str,
    token: str | None = None,
    private: bool | None = None,
    path_in_repo: str | None = None,
    commit_message: str | None = None,
    commit_description: str | None = None,
    create_repo_if_missing: bool = True,
    exist_ok: bool = True,
    generate_readme: bool = True,
    stats: dict[str, Any] | None = None,
    allow_patterns: Sequence[str] | None = None,
    ignore_patterns: Sequence[str] | None = None,
    delete_patterns: Sequence[str] | str | None = None,
) -> HfUploadResult:
    try:
        from huggingface_hub import HfApi, create_repo
    except Exception as exc:
        raise RuntimeError(
            "huggingface_hub is required for --hf-upload. Install with `pip install huggingface_hub` or reinstall the updated package dependencies."
        ) from exc

    export_root = export_root.resolve()
    if generate_readme:
        ensure_dataset_card(export_root, repo_id=repo_id, stats=stats or {})

    repo_url = f"https://huggingface.co/datasets/{repo_id}"
    created_repo = False
    if create_repo_if_missing:
        repo_url = str(create_repo(repo_id=repo_id, repo_type="dataset", private=private, exist_ok=exist_ok, token=token))
        created_repo = True

    api = HfApi(token=token)
    upload_result = api.upload_folder(
        folder_path=export_root,
        repo_id=repo_id,
        repo_type="dataset",
        path_in_repo=path_in_repo or None,
        commit_message=commit_message or "Upload scidatapipe export from top-papers-graph",
        commit_description=commit_description,
        allow_patterns=list(allow_patterns) if allow_patterns else None,
        ignore_patterns=list(ignore_patterns) if ignore_patterns else list(_DEFAULT_IGNORE),
        delete_patterns=delete_patterns,
        token=token,
    )
    return HfUploadResult(
        repo_id=repo_id,
        repo_url=repo_url,
        path_in_repo=path_in_repo or "",
        commit_message=commit_message or "Upload scidatapipe export from top-papers-graph",
        created_repo=created_repo,
        private=private,
        upload_result=upload_result,
    )
