from __future__ import annotations
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
PAPER_DIR = ROOT / "paper" / "agents4science"

def fail(msg: str) -> None:
    print(f"[FAIL] {msg}")
    sys.exit(1)

def ok(msg: str) -> None:
    print(f"[OK] {msg}")

def main() -> None:
    if not (PAPER_DIR / "main.tex").exists():
        fail("paper/agents4science/main.tex missing")
    ok("paper skeleton exists")

    txt = (PAPER_DIR / "main.tex").read_text(encoding="utf-8").lower()
    # naive anonymity checks: update as needed
    bad_tokens = ["mipt", "москов", "физтех", "stanford", "cian", "oh-team"]
    for tok in bad_tokens:
        if tok in txt:
            fail(f"Potentially identifying token in main.tex: '{tok}'")
    ok("basic anonymity scan passed (still manually review)")

    if not (PAPER_DIR / "fetch_template.sh").exists():
        fail("fetch_template.sh missing")
    ok("template fetch script present")

    print("\nManual checklist:")
    print("1) Page count <= 8 (excluding references/statements)")
    print("2) Official Agents4Science template used")
    print("3) AI Contribution Disclosure completed")
    print("4) Reproducibility statement present")
    print("5) Figures/tables are generated by scripts")
    print("6) No identifying info in PDF metadata")
    print("\nDone.")

if __name__ == "__main__":
    main()
